name: Deploy Static Site to Vercel

on:
  push:
    branches:
      - main  # o 'master' si tu rama principal se llama así

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull Vercel Environment Info
        run: vercel pull --yes --environment=production --token=$VERCEL_TOKEN

      - name: Deploy to Vercel
        run: vercel --prod --token=$VERCEL_TOKEN
